---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: integration-tests
  image: rancher/dapper:v0.6.0
  privileged: true
  settings:
    debug: true
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: default-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: integration-tests
  image: rancher/dapper:v0.6.0
  privileged: true
  settings:
    debug: true
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - push
    - tag
