---
kind: pipeline
name: provisioning-tests-k3s

platform:
  os: linux
  arch: amd64

environment:
  V2PROV_TEST_DIST: "k3s"
  V2PROV_TEST_RUN_REGEX: "^Test_(General|Provisioning)_.*$"

steps:
- name: provisioning-tests-pr
  image: rancher/dapper:v0.6.0
  commands:
  - dapper provisioning-tests
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
- name: provisioning-tests-push
  image: rancher/dapper:v0.6.0
  failure: ignore
  commands:
  - dapper provisioning-tests
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/master"
        - "refs/heads/release/v*"
        - "refs/tags/v*"
    event:
    - push

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote
---
kind: pipeline
name: provisioning-tests-rke2

platform:
  os: linux
  arch: amd64

environment:
  V2PROV_TEST_DIST: "rke2"
  V2PROV_TEST_RUN_REGEX: "^Test_(General|Provisioning)_.*$"

steps:
- name: provisioning-tests-pr
  image: rancher/dapper:v0.6.0
  commands:
  - dapper provisioning-tests
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
- name: provisioning-tests-push
  image: rancher/dapper:v0.6.0
  failure: ignore
  commands:
  - dapper provisioning-tests
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/master"
        - "refs/heads/release/v*"
        - "refs/tags/v*"
    event:
    - push

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote
---
kind: pipeline
name: provisioning-operations-tests-k3s

platform:
  os: linux
  arch: amd64

environment:
  V2PROV_TEST_DIST: "k3s"
  V2PROV_TEST_RUN_REGEX: "^Test_Operation_.*$"

steps:
  - name: provisioning-operations-tests-pr
    image: rancher/dapper:v0.6.0
    commands:
      - dapper provisioning-tests
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request
  - name: provisioning-operations-tests-push
    image: rancher/dapper:v0.6.0
    failure: ignore
    commands:
      - dapper provisioning-tests
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
          - "refs/tags/v*"
      event:
        - push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: provisioning-operations-test-setA-rke2

platform:
  os: linux
  arch: amd64

environment:
  V2PROV_TEST_DIST: "rke2"
  V2PROV_TEST_RUN_REGEX: "^Test_Operation_SetA_.*$"

steps:
  - name: provisioning-operations-tests-pr
    image: rancher/dapper:v0.6.0
    commands:
      - dapper provisioning-tests
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request
  - name: provisioning-operations-tests-push
    image: rancher/dapper:v0.6.0
    failure: ignore
    commands:
      - dapper provisioning-tests
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
          - "refs/tags/v*"
      event:
        - push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: provisioning-operations-test-setB-rke2

platform:
  os: linux
  arch: amd64

environment:
  V2PROV_TEST_DIST: "rke2"
  V2PROV_TEST_RUN_REGEX: "^Test_Operation_SetB_.*$"

steps:
  - name: provisioning-operations-tests-pr
    image: rancher/dapper:v0.6.0
    commands:
      - dapper provisioning-tests
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request
  - name: provisioning-operations-tests-push
    image: rancher/dapper:v0.6.0
    failure: ignore
    commands:
      - dapper provisioning-tests
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
          - "refs/tags/v*"
      event:
        - push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: check-release-images-exists
  image: rancher/dapper:v0.6.0
  failure: ignore
  commands:
  - dapper check-release-images-exist
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/tags/v*"
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote
---
kind: pipeline
name: docker-image-digests-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

# Currently have to define "depth" as otherwise clone fails at
# https://github.com/drone/drone-git/blob/39d233b3d9eccc68e66508a06a725a2567f33143/windows/clone-tag.ps1#L12
clone:
  depth: 20

steps:
- name: docker-image-digests
  image: rancher/drone-docker-image-digests:v0.0.12
  environment:
    PLUGIN_GITHUB_REPOSITORY: "rancher/rancher"
    PLUGIN_GITHUB_TOKEN:
      from_secret: github_token
    PLUGIN_GITHUB_TAG: "${DRONE_TAG}"
    PLUGIN_INPUT_FILE: "rancher-windows-images.txt"
    PLUGIN_OUTPUT_FILE: "rancher-images-digests-windows-1809.txt"
    PLUGIN_REGISTRY: "docker.io"
  volumes:
    - name: docker_pipe
      path: \\\\.\\pipe\\docker_engine
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
    - promote
    - pull_request

depends_on:
- default-linux-amd64
- default-windows-1809

---
kind: pipeline
name: docker-image-digests-windows-ltsc2022

platform:
  os: windows
  arch: amd64
  version: 2022

# Currently have to define "depth" as otherwise clone fails at
# https://github.com/drone/drone-git/blob/39d233b3d9eccc68e66508a06a725a2567f33143/windows/clone-tag.ps1#L12
clone:
  depth: 20

steps:
- name: docker-image-digests
  image: rancher/drone-docker-image-digests:v0.0.12
  environment:
    PLUGIN_GITHUB_REPOSITORY: "rancher/rancher"
    PLUGIN_GITHUB_TOKEN:
      from_secret: github_token
    PLUGIN_GITHUB_TAG: "${DRONE_TAG}"
    PLUGIN_INPUT_FILE: "rancher-windows-images.txt"
    PLUGIN_OUTPUT_FILE: "rancher-images-digests-windows-ltsc2022.txt"
    PLUGIN_REGISTRY: "docker.io"
  volumes:
    - name: docker_pipe
      path: \\\\.\\pipe\\docker_engine
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
    - promote
    - pull_request

depends_on:
- default-linux-amd64
- default-windows-ltsc2022
---
kind: pipeline
name: publish

platform:
  os: linux
  arch: amd64

steps:
- name: chart-promote
  image: rancher/dapper:v0.6.0
  commands:
  - dapper chart/copy
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - promote
    target:
    - promote-stable

- name: chart-publish
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "public,no-cache,proxy-revalidate"
    source: bin/chart
    target: releases.rancher.com/server-charts
    token:
      from_secret: google_auth_key
  when:
    event:
    - promote
    target:
    - promote-stable

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - promote
---
kind: pipeline
name: promote-docker-image

platform:
  os: linux
  arch: amd64

steps:
- name: docker-image-promote
  image: quay.io/skopeo/stable:v1.1.1
  commands:
  - echo $${DOCKER_PASSWORD} | skopeo login docker.io --username $${DOCKER_USERNAME} --password-stdin
  - skopeo copy docker://rancher/rancher:$${SOURCE_TAG} docker://rancher/rancher:$${DESTINATION_TAG} --all
  settings:
    custom_dns: 1.1.1.1
  volumes:
  - name: docker
    path: /var/run/docker.sock
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - promote
    target:
    - promote-docker-image

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - promote
