name: "Setup Dependencies Variables"
description: "Setup Dependencies Variables from other files"
outputs:
  CATTLE_KDM_BRANCH:
    description: "CATTLE_KDM_BRANCH from package/Dockerfile"
    value: ${{ steps.vars.outputs.CATTLE_KDM_BRANCH }} 
  CATTLE_K3S_VERSION: 
    description: "CATTLE_K3S_VERSION from package/Dockerfile"
    value: ${{ steps.vars.outputs.CATTLE_K3S_VERSION }}
  CATTLE_HELM_VERSION: 
    description: "CATTLE_HELM_VERSION from package/Dockerfile"
    value: ${{ steps.vars.outputs.CATTLE_HELM_VERSION }}
  HELM_VERSION: 
    description: "HELM_VERSION from package/Dockerfile"
    value: ${{ steps.vars.outputs.HELM_VERSION }}
  HELM_UNITTEST_VERSION: 
    description: "HELM_UNITTEST_VERSION from Dockerfile.dapper"
    value: ${{ steps.vars.outputs.HELM_UNITTEST_VERSION }}
  RKE_VERSION: 
    description: "RKE_VERSION from go.mod"
    value: ${{ steps.vars.outputs.RKE_VERSION }}
  CATTLE_RANCHER_WEBHOOK_VERSION: 
    description: "CATTLE_RANCHER_WEBHOOK_VERSION from scripts/export-config"
    value: ${{ steps.vars.outputs.CATTLE_RANCHER_WEBHOOK_VERSION }}
  CATTLE_CSP_ADAPTER_MIN_VERSION: 
    description: "CATTLE_CSP_ADAPTER_MIN_VERSION from scripts/export-config"
    value: ${{ steps.vars.outputs.CATTLE_CSP_ADAPTER_MIN_VERSION }}
  CATTLE_FLEET_VERSION: 
    description: "CATTLE_FLEET_VERSION from scripts/export-config"
    value: ${{ steps.vars.outputs.CATTLE_FLEET_VERSION }}
runs:
  using: "composite"
  steps:
    - id: vars
      shell: bash
      run: |
        echo "CATTLE_KDM_BRANCH=$(grep -m1 'ARG CATTLE_KDM_BRANCH=' package/Dockerfile | cut -d '=' -f2)" >> $GITHUB_OUTPUT
        echo "CATTLE_K3S_VERSION=$(grep -m1 'ENV CATTLE_K3S_VERSION' package/Dockerfile | awk '{print $3}')" >> $GITHUB_OUTPUT
        echo "HELM_VERSION=$(grep -m1 'ENV HELM_VERSION' package/Dockerfile | awk '{print $3}')" >> $GITHUB_OUTPUT
        echo "CATTLE_HELM_VERSION=$(grep -m1 'ENV CATTLE_HELM_VERSION' package/Dockerfile | awk '{print $3}')" >> $GITHUB_OUTPUT
        echo "CATTLE_HELM_VERSION=$(grep -m1 'ENV HELM_UNITTEST_VERSION' Dockerfile.dapper | awk '{print $3}')" >> $GITHUB_OUTPUT
        RKE_VERSION=$(grep -m1 'github.com/rancher/rke' go.mod | awk '{print $2}')
        if [[ -z "$RKE_VERSION" ]]; then
          RKE_VERSION=$(grep -m1 'github.com/rancher/rke' go.mod | awk '{print $4}')
        fi
        echo "RKE_VERSION=$RKE_VERSION" >> "$GITHUB_OUTPUT"
        source scripts/export-config
        echo "CATTLE_RANCHER_WEBHOOK_VERSION=$CATTLE_RANCHER_WEBHOOK_VERSION" >> "$GITHUB_OUTPUT"
        echo "CATTLE_CSP_ADAPTER_MIN_VERSION=$CATTLE_CSP_ADAPTER_MIN_VERSION" >> "$GITHUB_OUTPUT"
        echo "CATTLE_FLEET_VERSION=$CATTLE_FLEET_VERSION" >> "$GITHUB_OUTPUT"
