name: "Build Rancher Server"
description: "Build Rancher Docker image"
inputs:
  commit:
    description: "Commit SHA"
    required: true
  rke_version:
    description: "RKE version"
    required: true
  image:
    description: "Docker image name"
    required: true
  tag:
    description: "Docker image tag"
    required: true
  kdm_branch:
    description: "Kontainer Driver Metadata branch"
    required: true
  os:
    description: "Target operating system"
    required: true
  arch:
    description: "Target architecture"
    required: true
  push:
    description: "Push image to registry"
    required: false
    default: false"
runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        flavor: |
          latest=false
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Create k3s images file
      shell: bash
      run: touch k3s-airgap-images.tar
    - name: Download data.json
      shell: bash
      run: curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${{ inputs.kdm_branch }}/data.json > ./data.json
    - name: Build and export server
      id: build
      uses: docker/build-push-action@v5
      with:
        push: true
        build-args: |
          "VERSION=${{ inputs.commit }}"
          "COMMIT=${{ inputs.commit }}"
          "RKE_VERSION=${{ inputs.rke_version }}"
          "ARCH=${{ inputs.arch }}"
        tags: ${{ inputs.image }}:${{ inputs.tag }}
        context: .
        platforms: "${{ inputs.os }}/${{ inputs.arch }}"
        file: ./package/Dockerfile
        labels: "${{ steps.meta.outputs.labels }}"
