name: Build and test PR
on:
  - pull_request
env:
  ARCH: amd64
  TAG: ${{ github.ref_name }}
  GIT_TAG: ${{ github.ref_name }}
  HEAD_TAG: ${{ github.ref_name }}
  COMMIT: ${{ github.sha }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE: ${{ github.repository_owner }}/rancher
  IMAGE_AGENT: ${{ github.repository_owner }}/rancher-agent
  IMAGE_INSTALLER: ${{ github.repository_owner }}/system-agent-installer-rancher
  CATTLE_KDM_BRANCH: dev-v2.8
  HELM_UNITTEST_VERSION: 0.3.2
  HELM_URL_V3: https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          zypper -n install gawk python311-pip python311-base python311 python311-devel python311-tox libffi-devel libopenssl-devel
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.2; \
      - name: Validate
        run: ./scripts/validate