name: Integration Tests
on: [workflow_call]
jobs:
  integration_tests:
    name: Integration tests 
    runs-on: runs-on,runner=4cpu-linux-x64,image=legacy-cgroups-for-x64,run-id=${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dapper
        run: |
          curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > ./.dapper
          chmod +x ./.dapper
      - name: Run tests
        run: ./.dapper ci