name: Unit Tests
on:
  workflow_call:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          go test -cover -tags=test ./pkg/...
